### ISSUE TITLE
How to use the calibration data

### ISSUE THREAD

**Issue by Hugal31** [iaslab-unipd/rgbd_calibration#14]
Hello.

I think I have successfully obtained the calibration data, and as a result the software created two files, global_matrix.txt and local_matrix.txt

I have multiple questions:
- How can I use the results of the calibration, say, with ROS. Did someone developed a ROS node that apply the calibration on a raw depth image ? I didn't see anything like it in this repository.
- What is the format of global_matrix.txt and local_matrix.txt ? I understand they contain polynomial functions, but which one correspond to which pixel ?
- Why do I only have 77361 polynomial functions in local_matrix.txt when I have 640x480 = 307200 pixels, with a bin size of 1x1 (i.e. the undistortion_matrix parameter of the rgbd_offile_calibration node to 1x1) ?

**Comment by Hugal31** [comment]
Ok, I got it.

- I quickly developed a ROS nodelet using the rgbd_calibration code.
- I suppose the two files contains the matrix in the order colums then rows, but I read them with `PolynomialUndistortionMatrixIO` anyway.
- I let the parameter `downsample_ratio` to 2, so I had an image of 320x240, + 1 because of the binning which overflow the image by 1, so 321x241 = 77361

**Comment by johaq** [comment]
Is your developed node publicly available?
I would be very interested.

**Comment by Hugal31** [comment]
@johaq 

I uploaded my nodelet at https://github.com/Hugal31/depth_correction.
You may also be interested by my changes made to the original calibration code to make it work with ROS kinetic : https://github.com/Hugal31/rgbd_calibration

**Comment by alphjheon** [comment]
@Hugal31  i try to use the project provided by @bassofil. After running offline calibration, when i use my test set. After calling to addData() function (test_node) line 36x , cloud_rgb is empty. Did you face any similar issues when running your node? Also could you please refer to your parameters on launch file(eg. downsample_ratio) and dataset structure (rgb or raw point cloud). I used downsample_ratio = 1  for testing.

**Comment by Hugal31** [comment]
I didn't investigate too much test_node, I assumed it didn't fit my needs.
Be careful, with a downsampling_ratio of 1, the RAM consumption can grow very high.

**Comment by alphjheon** [comment]
Ok i understand. As for offline calibration, and the input. What are your initial values for camera pose(translation & rotation). I use the same parameters as repo ( translation: {x: 0, y: 0, z: 0}
            rotation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0} )
and i got strange optimized transform (orientation with nan's).

**Comment by Hugal31** [comment]
That's strange. I got something like this with an AsusXtion Pro Live:
```yaml
translation: {x: -0.00286094, y: -0.0495885, z: 0.0991642}
rotation: {x: 0.000789559, y: -0.00598455, z: 0.00299283, w: 0.999977}
```

**Comment by alphjheon** [comment]
These are your initial values given with launch file? didn't understand you

**Comment by Hugal31** [comment]
My parameters were also translation: {x: 0, y: 0, z: 0}
rotation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}, and the calibration gave me
```yaml
translation: {x: -0.00286094, y: -0.0495885, z: 0.0991642}
rotation: {x: 0.000789559, y: -0.00598455, z: 0.00299283, w: 0.999977}
```

**Comment by alphjheon** [comment]
This is actually, strange. Could you describe my your data? Is it a checkerboard inf front of a wall(full planar)?

**Comment by Hugal31** [comment]
Yes, the checkerboard is sticked to the wall, and I payed attention to not frame the floor or nothing else. I join a part of my samples as an example, and the camera info files.

[data-collection.tar.gz](https://github.com/iaslab-unipd/rgbd_calibration/files/2816450/data-collection.tar.gz)

**Comment by Hugal31** [comment]
No, I didn't. What's the problem?

**Comment by alphjheon** [comment]
It has been solved (something with calibration toolkit version). The problem running with your data is this:

[ After launching the node, i got a screen with "select checkerboard" that does nothing, and after i close this i got an openCV error OpenCV Error: Assertion failed (ssize.area() > 0) in resize, file path/opencv-2.4.13/modules/imgproc/src/imgwarp.cpp, line 1968
terminate called after throwing an instance of 'cv::Exception'
  what():  Path/opencv-2.4.13/modules/imgproc/src/imgwarp.cpp:1968: error: (-215) ssize.area() > 0 in function resize
](url) 
I guess it has to do with input pixels but it is strange.

**Comment by pyni** [comment]
Hi~ have you solved problem?

**Comment by Hugal31** [comment]
Hum, this is old so I don't remember. I marked the issue as closed so I suppose I got everything working.

Someone, who obviously deleted his comments, asked me for help.

**Comment by pyni** [comment]
Thanks for replying. I haven't tried yet.
I just wonder how accurate is this code (or this algorithm)?   
Is the calibration result of this algorithm better than the default parameters for cameras, such as asus?

**Comment by Hugal31** [comment]
I remember both can be used together: first you apply the pinhole model parameters, then you can use this algorithm. The results are good, but I haven't achieved a "near-perfect" correction. My calibration data was not excellent, though.

**Comment by pyni** [comment]
Thanks! I'll try it later.

**Comment by Tiansong97** [comment]
> Yes, the checkerboard is sticked to the wall, and I payed attention to not frame the floor or nothing else. I join a part of my samples as an example, and the camera info files.
> 
> [data-collection.tar.gz](https://github.com/iaslab-unipd/rgbd_calibration/files/2816450/data-collection.tar.gz)

Can you provide some more datasets? I feel confused about the camera info. The format of the camera info that collected(file: image_camera_info.yaml) is different from the format that is input(file: rgb_PS1080_PrimeSense.yaml to the calib algorithm, did you convert it manually? Besides, the examples you provided didn't include depth images?

**Comment by Tiansong97** [comment]
> Yes, the checkerboard is sticked to the wall, and I payed attention to not frame the floor or nothing else. I join a part of my samples as an example, and the camera info files.
> 
> [data-collection.tar.gz](https://github.com/iaslab-unipd/rgbd_calibration/files/2816450/data-collection.tar.gz)
Can you provide some more datasets? I feel confused about the camera info. The format of the camera info that collected(file: image_camera_info.yaml) is different from the format that is input(file: rgb_PS1080_PrimeSense.yaml) to the calib algorithm, did you convert it manually? Besides, the examples you provided didn't include depth images?

**Comment by tiexuedanxin** [comment]
> Hello.
> 
> I think I have successfully obtained the calibration data, and as a result the software created two files, global_matrix.txt and local_matrix.txt
> 
> I have multiple questions:
> 
> * How can I use the results of the calibration, say, with ROS. Did someone developed a ROS node that apply the calibration on a raw depth image ? I didn't see anything like it in this repository.
> * What is the format of global_matrix.txt and local_matrix.txt ? I understand they contain polynomial functions, but which one correspond to which pixel ?
> * Why do I only have 77361 polynomial functions in local_matrix.txt when I have 640x480 = 307200 pixels, with a bin size of 1x1 (i.e. the undistortion_matrix parameter of the rgbd_offile_calibration node to 1x1) ?

hello, I am using your data to calibrate, but I don't know how to do it, Could you give me some guide.

**Comment by Hugal31** [comment]
Hello,

I didn't used this process for a while, so I only have vague memories. Look at [my fork of this repository](https://github.com/Hugal31/rgbd_calibration).
Note that there is no point to calibrate your camera with my data. You must capture your own data.

**Comment by tiexuedanxin** [comment]
> Hello,
> 
> I didn't used this process for a while, so I only have vague memories. Look at [my fork of this repository](https://github.com/Hugal31/rgbd_calibration).
> Note that there is no point to calibrate your camera with my data. You must capture your own data.

hello, I have download your repository and calibration_toolkit-0.3, but when I catkin_make the package the following error occured. Could you give me some advice on how to solve it, very thanks.

/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h:92:17: error: ‘class calibration::PolynomialMatrixSmoothModelFitPCL<calibration::Polynomial<double, 2>, double, pcl::PointXYZ>’ has no member named ‘setDepthErrorFunction’
     local_fit_->setDepthErrorFunction(depth_error_function_);
                 ^~~~~~~~~~~~~~~~~~~~~
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h: In member function ‘void calibration::DepthUndistortionEstimation::setGlobalModel(const Ptr&)’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h:99:18: error: ‘class calibration::PolynomialMatrixSmoothModelFitPCL<calibration::Polynomial<double, 2, 1>, double, pcl::PointXYZ>’ has no member named ‘setDepthErrorFunction’
     global_fit_->setDepthErrorFunction(depth_error_function_);
                  ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:46:0:
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h: In member function ‘void calibration::DepthUndistortionEstimation::setLocalModel(const Ptr&)’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h:92:17: error: ‘class calibration::PolynomialMatrixSmoothModelFitPCL<calibration::Polynomial<double, 2>, double, pcl::PointXYZ>’ has no member named ‘setDepthErrorFunction’
     local_fit_->setDepthErrorFunction(depth_error_function_);
                 ^~~~~~~~~~~~~~~~~~~~~
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h: In member function ‘void calibration::DepthUndistortionEstimation::setGlobalModel(const Ptr&)’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/depth_undistortion_estimation.h:99:18: error: ‘class calibration::PolynomialMatrixSmoothModelFitPCL<calibration::Polynomial<double, 2, 1>, double, pcl::PointXYZ>’ has no member named ‘setDepthErrorFunction’
     global_fit_->setDepthErrorFunction(depth_error_function_);
                  ^~~~~~~~~~~~~~~~~~~~~
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp: In member function ‘bool calibration::TransformError::operator()(const T*, const T*, T*) const’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:359:68: error: ‘const class calibration::PinholeCameraModel’ has no member named ‘project3dToPixel2’; did you mean ‘project3dToPixel’?
     typename Types<T>::Cloud2 reprojected_corners = camera_model_->project3dToPixel2<T>(cb_corners);
                                                                    ^~~~~~~~~~~~~~~~~
                                                                    project3dToPixel
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:359:87: error: expected primary-expression before ‘>’ token
     typename Types<T>::Cloud2 reprojected_corners = camera_model_->project3dToPixel2<T>(cb_corners);
                                                                                       ^
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp: In member function ‘bool calibration::ReprojectionError::operator()(const T*, const T*, T*) const’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:469:49: error: ‘const class calibration::PinholeCameraModel’ has no member named ‘project3dToPixel2’; did you mean ‘project3dToPixel’?
         reprojected_corners[i] = camera_model_->project3dToPixel2<T>(cb_corners[i]);
                                                 ^~~~~~~~~~~~~~~~~
                                                 project3dToPixel
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:469:68: error: expected primary-expression before ‘>’ token
         reprojected_corners[i] = camera_model_->project3dToPixel2<T>(cb_corners[i]);
                                                                    ^
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp: In member function ‘bool calibration::TransformDistortionError::operator()(const T*, const T*, const T*, const T*, const T*, const T*, T*) const’:
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:588:57: error: ‘const class calibration::KinectDepthCameraModel’ has no member named ‘undistort2d_’
           depth_points(i, j) = z * depth_camera_model_->undistort2d_<T>(normalized_pixel).homogeneous();
                                                         ^~~~~~~~~~~~
/home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:588:71: error: expected primary-expression before ‘>’ token
           depth_points(i, j) = z * depth_camera_model_->undistort2d_<T>(normalized_pixel).homogeneous();
                                                                       ^
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model_normal_plane.h:44,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model_normal_parallel_plane.h:44,
                 from /home/yong/test_ws/src/calibration_toolkit-0.3/calibration_common/include/calibration_common/algorithms/plane_extraction.h:43,
                 from /home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/checkerboard_views.h:35,
                 from /home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/depth_undistortion_estimation.cpp:40:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
In file included from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model.h:52:0,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model_normal_plane.h:44,
                 from /usr/include/pcl-1.8/pcl/sample_consensus/sac_model_normal_parallel_plane.h:44,
                 from /home/yong/test_ws/src/calibration_toolkit-0.3/calibration_common/include/calibration_common/algorithms/plane_extraction.h:43,
                 from /home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/checkerboard_views.h:35,
                 from /home/yong/test_ws/src/rgbd_calibration-kinetic/include/rgbd_calibration/checkerboard_views_extractor.h:33,
                 from /home/yong/test_ws/src/rgbd_calibration-kinetic/src/rgbd_calibration/calibration.cpp:44:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h: In function ‘void __static_initialization_and_destruction_0(int, int)’:
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: warning: ‘pcl::SAC_SAMPLE_SIZE’ is deprecated: This map is deprecated and is kept only to prevent breaking existing user code. Starting from PCL 1.8.0 model sample size is a protected member of the SampleConsensusModel class [-Wdeprecated-declarations]
   SAC_SAMPLE_SIZE (sample_size_pairs, sample_size_pairs + sizeof (sample_size_pairs) / sizeof (SampleSizeModel));
   ^~~~~~~~~~~~~~~
/usr/include/pcl-1.8/pcl/sample_consensus/model_types.h:99:3: note: declared here
rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/build.make:86: recipe for target 'rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/src/rgbd_calibration/depth_undistortion_estimation.cpp.o' failed
make[2]: *** [rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/src/rgbd_calibration/depth_undistortion_estimation.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/build.make:62: recipe for target 'rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/src/rgbd_calibration/calibration.cpp.o' failed
make[2]: *** [rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/src/rgbd_calibration/calibration.cpp.o] Error 1
CMakeFiles/Makefile2:4756: recipe for target 'rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/all' failed
make[1]: *** [rgbd_calibration-kinetic/CMakeFiles/rgbd_calibration.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed

**Comment by Hugal31** [comment]
Sorry, I don't know. Make sure you are using calibration_toolkit 3.**2**.

**Comment by tiexuedanxin** [comment]
> Sorry, I don't know. Make sure you are using calibration_toolkit 3.**2**.

hello, If I catkin_make the package successful and use your data to run the process. is the code need to modify such as the kinect_47A_tro.launch file and other code.
