### ISSUE TITLE
Distortion is unknown - Offline caliberation node crashes

### ISSUE THREAD

**Issue by ghost** [iaslab-unipd/rgbd_calibration#5]
Executing `roslaunch rgbd_calibration kinect_47A_tro.launch` results in ROS crashing with the error:
```
Calibration error: Cannot call rectifyImage when distortion is unknown.
```

Most likely this is due to `offline_calibration_node.cpp` utilizing `color_sensor_` and `depth_sensor_` variables with its defaults. `setColorSensor` or `setDepthSensor` does not seem to be called.

Do you expect the cameras to be calibrated by another software (has its parameters estimated somehow beforehand)? If no, then I expect you can reproduce this issue if you remove your camera calibration files, and execute the above launcher..

This way I cannot utilize this library at all.. Can you advice with a solution?

**Comment by bassofil** [comment]
Sahloul, calibrating the intrinsics of camera goes beyond the scope of the work, especially because there are tons of other applications for that purpose. The software, as you pointed out, expects the cameras to be calibrated using standard ROS calibration tools.
